const edges = [
  { source: "SoftwareProduct", target: "ApplicationSystemTypeCitation", name: "is of" },
  { source: "SoftwareProduct", target: "EnterpriseFunctionCitation" },
  { source: "SoftwareProduct", target: "FeatureCitation", name: "offers" },
  { source: "SoftwareProduct", target: "OrganizationalUnitCitation" },
  { source: "SoftwareProduct", target: "UserGroupCitation" },
  { source: "Study", target: "SoftwareProduct" },
  { source: "SoftwareProduct", target: "ApplicationSystemTypeCitation" },
  { source: "EnterpriseFunctionCitation", target: "EnterpriseFunctionClassified" },
  { source: "ApplicationSystemTypeCitation", target: "ApplicationSystemTypeClassified" },
  { source: "EnterpriseFunctionCitation", target: "EnterpriseFunctionClassified" },
  { source: "FeatureCitation", target: "FeatureClassified" },
  { source: "OrganizationalUnitCitation", target: "OrganizationalUnitClassified" },
  { source: "UserGroupCitation", target: "UserGroupClassified" },
  { source: "ApplicationSystemTypeCitation", target: "EnterpriseFunctionCitation", name: "supports" },
  { source: "ApplicationSystemTypeClassified", target: "EnterpriseFunctionClassified", name: "supports" },
];
