export const edges = {
  spIsOfAstCit: { source: "SoftwareProduct", target: "ApplicationSystemTypeCitation", name: "is of" },
  spSupportsEfCit: { source: "SoftwareProduct", target: "EnterpriseFunctionCitation", name: "supports" },
  spOffersFCit: { source: "SoftwareProduct", target: "FeatureCitation", name: "offers" },
  spUsedInOuCit: { source: "SoftwareProduct", target: "OrganizationalUnitCitation", name: "used in" },
  spUsedByUserCit: { source: "SoftwareProduct", target: "UserGroupCitation", name: "used by" },
  evaluatesProduct: { source: "Study", target: "SoftwareProduct", name: "evaluates" },
  evaluatesApplicationSystemType: { source: "Study", target: "ApplicationSystemTypeCitation", name: "evaluates" },
  evaluatesApplicationSystemTypeHavingFeature: { source: "Study", target: "FeatureCitation", name: "evaluates" },
  ocEvaluatesOcCit: { source: "Study", target: "OutcomeCriteriaCitation", name: "evaluates" },
  evaluatesApplicationSystemTypeHavingUserGroup: {
    source: "Study",
    target: "UserGroupCitation",
    name: "evaluates application system or software product used by",
  },
  evaluatesApplicationSystemTypeUsedInUnit: {
    source: "Study",
    target: "OrganizationalUnitCitation",
    name: "evaluates application system or software product used in",
  },
  efCitClassifiedAs: { source: "EnterpriseFunctionCitation", target: "EnterpriseFunctionClassified", name: "classified as" },
  efClaFrom: { source: "EnterpriseFunctionClassified", target: "EnterpriseFunctionCatalogue", name: "from catalogue" },
  //"supportedByFeatureCitation": {source: "EnterpriseFunctionCitation", target: "FeatureCitation", name: "supported by feature citation", }, // overlap in display
  astCitClassifiedAs: { source: "ApplicationSystemTypeCitation", target: "ApplicationSystemTypeClassified", name: "classified as" },
  astClaFrom: { source: "ApplicationSystemTypeClassified", target: "ApplicationSystemTypeCatalogue", name: "from catalogue" },
  astClaSupportsEfCla: { source: "ApplicationSystemTypeClassified", target: "EnterpriseFunctionClassified", name: "supports" },
  fCitClassifiedAs: { source: "FeatureCitation", target: "FeatureClassified", name: "classified as" },
  fClaFrom: { source: "FeatureClassified", target: "FeatureCatalogue", name: "from catalogue" },
  ocCitClassifiedAs: { source: "OutcomeCriteriaCitation", target: "OutcomeCriteriaClassified", name: "classified as" },
  ouCitClassifiedAs: { source: "OrganizationalUnitCitation", target: "OrganizationalUnitClassified", name: "classified as" },
  ouClaFrom: { source: "OrganizationalUnitClassified", target: "OrganizationalUnitCatalogue", name: "classified as" },
  userCitClassifiedAs: { source: "UserGroupCitation", target: "UserGroupClassified", name: "classified as" },
  userClaFrom: { source: "UserGroupClassified", target: "UserGroupCitation", name: "classified as" },
  supportsFunction: { source: "FeatureCitation", target: "EnterpriseFunctionCitation", name: "supports function citation" },
  supportsFunctionClassified: { source: "FeatureClassified", target: "EnterpriseFunctionClassified", name: "supports classified function" },
  studyMethod: { source: "Study", target: "StudyMethod", name: "study method" },
  //"": {source: "ApplicationSystemTypeCitation", target: "EnterpriseFunctionCitation", name: "supports", }, // in dia 22.05 but not in ontology
  interoperability: { source: "SoftwareProduct", target: "Interoperability", name: "interoperability" },
  firstAuthor: { source: "Study", target: "FirstAuthor", name: "first author" },
  databaseSystem: { source: "SoftwareProduct", target: "DatabaseSystem", name: "uses DBMS" },
  certification: { source: "SoftwareProduct", target: "Certification", name: "certified by" },
  language: { source: "SoftwareProduct", target: "Language", name: "available in" },
  license: { source: "SoftwareProduct", target: "License", name: "uses license" },
  homepage: { source: "SoftwareProduct", target: "Client", name: "homepage" },
  operatingSystem: { source: "SoftwareProduct", target: "OperatingSystem", name: "available for" },
  programmingLanguage: { source: "SoftwareProduct", target: "ProgrammingLanguage", name: "written in" },
  programmingLibrary: { source: "SoftwareProduct", target: "ProgrammingLibrary", name: "uses library" },
  pmid: { source: "Study", target: "PMID", name: "has PMID" },
  publishedInYear: { source: "Study", target: "gYear", name: "published in year" },
  publishedInJournal: { source: "Study", target: "Journal", name: "published in journal" },
};
