export const nodes = {
  SoftwareProduct: { name: "Software Product" },
  EnterpriseFunctionClassified: { name: "Enterprise Function Classified" },
  EnterpriseFunctionCitation: { name: "Enterprise Function Citation" },
  ApplicationSystemTypeCitation: { name: "Application System Type Citation" },
  ApplicationSystemTypeClassified: { name: "Application System Type Classified" },
  FeatureCitation: { name: "Feature Citation" },
  FeatureClassified: { name: "Feature Classified" },
  OrganizationalUnitCitation: { name: "Organizational Unit Citation" },
  OrganizationalUnitClassified: { name: "Organizational Unit Classified" },
  UserGroupCitation: { name: "User Group Citation" },
  UserGroupClassified: { name: "User Group Classified" },
  Study: { name: "Study" },
  FirstAuthor: { name: "First Author", type: "string" },
  Interoperability: { name: "Interoperability Standard" },
};
