export const nodes = {
  SoftwareProduct: { name: "Software Product" },
  EnterpriseFunctionClassified: { name: "Enterprise Function Classified" },
  EnterpriseFunctionCitation: { name: "Enterprise Function Citation" },
  EnterpriseFunctionCatalogue: { name: "Enterprise Function Catalogue" },
  ApplicationSystemTypeCitation: { name: "Application System Type Citation" },
  ApplicationSystemTypeClassified: { name: "Application System Type Classified" },
  ApplicationSystemTypeCatalogue: { name: "Application System Type Catalogue" },
  FeatureCitation: { name: "Feature Citation" },
  FeatureClassified: { name: "Feature Classified" },
  FeatureCatalogue: { name: "Feature Catalogue" },
  OutcomeCriteriaCitation: { name: "Outcome Criteria Citation" },
  OutcomeCriteriaClassified: { name: "Outcome Criteria Classified" },
  OrganizationalUnitCitation: { name: "Organizational Unit Citation" },
  OrganizationalUnitClassified: { name: "Organizational Unit Classified" },
  OrganizationalUnitCatalogue: { name: "Organizational Unit Catalogue" },
  UserGroupCitation: { name: "User Group Citation" },
  UserGroupClassified: { name: "User Group Classified" },
  UserGroupCatalogue: { name: "User Group Catalogue " },
  Study: { name: "Study" },
  StudyMethod: { name: "Study Method" },
  FirstAuthor: { name: "First Author", type: "string" },
  Interoperability: { name: "Interoperability Standard" },
  DatabaseSystem: { name: "Database System" },
  Certification: { name: "Certification" },
  Client: { name: "Client" },
  Language: { name: "Language" },
  License: { name: "License" },
  OperatingSystem: { name: "Operating System" },
  ProgrammingLanguage: { name: "Programming Language" },
  ProgrammingLibrary: { name: "Programming Library" },
  PMID: { name: "PMID" },
  gYear: { name: "Year", type: "string" },
  Journal: { name: "Journal" },
};
